version: 0.2
phases:
  pre_build:
    commands:
      - npm install --unsafe-perm -g gatsby
  build:
    commands:
      - cp .env.$ENV .env
      - npm install
      - gatsby clean && gatsby build
      - echo "******** Cleaning S3 objects ********"
      - aws s3 rm $S3_BUCKET --recursive
artifacts:
  files:
    - '**/*'
  base-directory: public
